# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/gcapo/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-10708-Notebook-Guille/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -ruleid {1}  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal_vvd/NCO senoidal.runs/synth_1}}  -suppress 
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.cache/wt} [current_project]
set_property parent.project_path {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-10:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Fuentes/acumulador.vhd}
  {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Fuentes/cfa_seno.vhd}
  {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Fuentes/seno.vhd}
  {C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Fuentes/seno_vio_ila.vhd}
}
read_ip -quiet {{C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/vio_0/vio_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/vio_0/vio_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc}}]

read_ip -quiet {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/ila_0/ila_0.xci}}
set_property used_in_synthesis false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/constrs_1/imports/Clase 4 - FPGA/Arty-Z7-10-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/gcapo/Documents/CESE_docs/04 FPGA/TP/NCO_senoidal/Vivado_ILA/NCO senoidal ILA.srcs/constrs_1/imports/Clase 4 - FPGA/Arty-Z7-10-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top seno_VIO_ILA -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef seno_VIO_ILA.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file seno_VIO_ILA_utilization_synth.rpt -pb seno_VIO_ILA_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
